[server]
# Disable file watcher for production (prevents auto-reload)
fileWatcherType = "none"

# Increase timeouts for long-running operations
maxUploadSize = 200
enableCORS = false

# Session management
maxConcurrentUsers = 10

[runner]
# Allow long-running operations without timeout
fastReruns = false

[client]
# Show details during processing
showErrorDetails = true

