# Local development secrets (NOT committed to git)
# In production, these are configured in Streamlit Cloud's secrets UI

open_ai = "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"
gemini_api_key = "AIzaSyAnmI0sWrLlV5_UXVBBoyHkU2DvBdLlTjs"
