# ========================================
# WMS LLM Agent - API Keys Configuration
# ========================================

# 🔑 OpenAI API Key (Primary - ₹300 credits)
# Current status: Key is valid but project needs budget allocation
# Once you allocate budget at https://platform.openai.com/settings/organization/projects
# this will work automatically!
open_ai = "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"

# 🔑 Google Gemini API Key (Fallback - Free)
# This is your existing working Gemini key:
gemini_api_key = "AIzaSyAnmI0sWrLlV5_UXVBBoyHkU2DvBdLlTjs"
google_api_key = "AIzaSyAnmI0sWrLlV5_UXVBBoyHkU2DvBdLlTjs"

# ========================================
# How to Use:
# ========================================
# 1. Create a NEW OpenAI API key at:
#    https://platform.openai.com/api-keys
#
# 2. Make sure to:
#    - Select project: proj_lwkWsrx92QwuR289Q4EeQt5f
#    - Allocate budget (₹100 or ₹300)
#
# 3. Copy your new key (starts with sk-proj-...)
#
# 4. Replace "sk-proj-YOUR_NEW_KEY_HERE" above with your actual key
#
# 5. Save this file
#
# 6. Restart Streamlit app
#
# ========================================
# System Behavior:
# ========================================
# - Tries OpenAI FIRST (if key is valid and has budget)
# - Falls back to Gemini FREE (if OpenAI fails)
# - Automatically switches between them as needed
# ========================================

