# Local development secrets (NOT committed to git)
# In production, these are configured in Streamlit Cloud's secrets UI

open_ai = "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"
gemini_api_key = "AIzaSyAnmI0sWrLlV5_UXVBBoyHkU2DvBdLlTjs"
